== Другие применения адаптеров
Многие функции Qt возвращают последовательности указателей на базовые классы:

* `QObject`
* `QWidget`
* `QGraphicsItem`

== Методы приведения типов
* `dynamic_cast`
* `static_cast`
* `qobject_cast`

[%notitle]
== Пример приведения типа
[source,c++,linenums,highlight='11..18|1..9|15']
----
include::../test/downcasting.cpp[tag=caster]

include::../test/downcasting.cpp[tag=iterate0]
----

== `boost::adaptors::filtered`
[source,c++,linenums,highlight='3']
----
include::../test/downcasting.cpp[tag=iterate1]
----

== `boost::for_each`
[source,c++,linenums]
----
include::../test/downcasting.cpp[tag=iterate2]
----

== Свой адаптер приведения типа
* Функциональный объект, переопределяющий `operator|`
* Диапазон (`boost::iterator_range`)
* Итератор (Boost.StlInterfaces)

[%notitle]
== Объявление итератора приведения
[source,c++,linenums,highlight='|3|3..4|5|6|7|11-12|13']
----
include::../test/downcasting.cpp[tag=cast_iter_begin]
  ...
include::../test/downcasting.cpp[tag=cast_iter_end]
----
<1> CRTP
<2> Категория итератора
<3> Тип значения
<4> Тип ссылки

== Фильтруюущая часть
[source,c++,linenums,highlight='|1|3|8|14|16']
----
include::../test/downcasting.cpp[tag=cast_iter_filter]

include::../test/downcasting.cpp[tag=cast_iter_advance]
----
<1> Кэшируем полученное значение


== Трансформирующая часть
[source,c++,linenums]
----
include::../test/downcasting.cpp[tag=cast_iter_trans]
----

== Возвращаем ссылку
[source,c++,linenums,highlight='|6,8..9']
----
include::../test/downcasting.cpp[tag=cast_iter_trans2]
----
<1> Тип значения -- `T`

== Адаптер
[source,c++,linenums,highlight='|7..11|17']
----
include::../test/downcasting.cpp[tag=cast_adaptor]
----
<1> Создание диапазона (`boost::iterator_range`)
<2> Boost.HOF

[%notitle.columns]
== Приведение: сравним исходный цикл и результирующий
[.column]
--
[source,c++,linenums]
----
include::../test/downcasting.cpp[tag=iterate4]
----
--

[%step.column]
--
[source,c++,linenums]
----
include::../test/downcasting.cpp[tag=iterate0]
----
--
